In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('train.csv')
df

ID                                          dri_score psych_disturb  \
0          0                     N/A - non-malignant indication            No   
1          1                                       Intermediate            No   
2          2                     N/A - non-malignant indication            No   
3          3                                               High            No   
4          4                                               High            No   
...      ...                                                ...           ...   
28795  28795  Intermediate - TED AML case <missing cytogenetics           NaN   
28796  28796                                               High            No   
28797  28797                                   TBD cytogenetics           NaN   
28798  28798                     N/A - non-malignant indication            No   
28799  28799                                    N/A - pediatric            No   

         cyto_score diabetes  hla_match_c_high  hla_high_res_8  \
0               NaN       No               NaN             NaN   
1      Intermediate       No               2.0             8.0   
2               NaN       No               2.0             8.0   
3      Intermediate       No               2.0             8.0   
4               NaN       No               2.0             8.0   
...             ...      ...               ...             ...   
28795     Favorable       No               2.0             8.0   
28796          Poor      Yes               1.0             4.0   
28797          Poor      NaN               2.0             8.0   
28798          Poor       No               1.0             4.0   
28799           NaN       No               2.0             8.0   

               tbi_status arrhythmia  hla_low_res_6  ...  \
0                  No TBI         No            6.0  ...   
1      TBI +- Other, >cGy         No            6.0  ...   
2                  No TBI         No            6.0  ...   
3                  No TBI         No            6.0  ...   
4                  No TBI         No            6.0  ...   
...                   ...        ...            ...  ...   
28795              No TBI         No            6.0  ...   
28796              No TBI         No            5.0  ...   
28797              No TBI        NaN            6.0  ...   
28798              No TBI         No            3.0  ...   
28799              No TBI         No            6.0  ...   

                       tce_div_match donor_related      melphalan_dose  \
0                                NaN     Unrelated  N/A, Mel not given   
1              Permissive mismatched       Related  N/A, Mel not given   
2              Permissive mismatched       Related  N/A, Mel not given   
3              Permissive mismatched     Unrelated  N/A, Mel not given   
4              Permissive mismatched       Related                 MEL   
...                              ...           ...                 ...   
28795  Bi-directional non-permissive           NaN  N/A, Mel not given   
28796             GvH non-permissive       Related  N/A, Mel not given   
28797             GvH non-permissive     Unrelated  N/A, Mel not given   
28798          Permissive mismatched       Related                 MEL   
28799          Permissive mismatched       Related                 MEL   

      hla_low_res_8 cardiac  hla_match_drb1_high pulm_moderate  \
0               8.0      No                  2.0            No   
1               8.0      No                  2.0           Yes   
2               8.0      No                  2.0            No   
3               8.0      No                  2.0            No   
4               8.0      No                  2.0            No   
...             ...     ...                  ...           ...   
28795           8.0     NaN                  2.0            No   
28796           6.0     Yes                  1.0           Yes   
28797           8.0     NaN             

In [8]:
df.isnull().sum()

ID                            0
dri_score                   154
psych_disturb              2062
cyto_score                 8068
diabetes                   2119
hla_match_c_high           4620
hla_high_res_8             5829
tbi_status                    0
arrhythmia                 2202
hla_low_res_6              3270
graft_type                    0
vent_hist                   259
renal_issue                1915
pulm_severe                2135
prim_disease_hct              0
hla_high_res_6             5284
cmv_status                  634
hla_high_res_10            7163
hla_match_dqb1_high        5199
tce_imm_match             11133
hla_nmdp_6                 4197
hla_match_c_low            2800
rituximab                  2148
hla_match_drb1_low         2643
hla_match_dqb1_low         4194
prod_type                     0
cyto_score_detail         11923
conditioning_intensity     4789
ethnicity                   587
year_hct                      0
obesity                    1760
mrd_hct 

In [10]:
# Checking missing values percentage
missing_values = df.isnull().sum() / len(df) * 100
missing_values = missing_values[missing_values > 0].sort_values(ascending=False)

In [12]:
missing_values

tce_match                 65.958333
mrd_hct                   57.628472
cyto_score_detail         41.399306
tce_div_match             39.569444
tce_imm_match             38.656250
cyto_score                28.013889
hla_high_res_10           24.871528
hla_high_res_8            20.239583
hla_high_res_6            18.347222
hla_match_dqb1_high       18.052083
hla_low_res_10            17.583333
conditioning_intensity    16.628472
hla_match_c_high          16.041667
hla_match_a_high          14.934028
hla_nmdp_6                14.572917
hla_match_dqb1_low        14.562500
hla_match_b_high          14.194444
hla_low_res_8             12.684028
hla_match_drb1_high       11.638889
hla_low_res_6             11.354167
hla_match_c_low            9.722222
hla_match_drb1_low         9.177083
hla_match_b_low            8.906250
cardiac                    8.826389
peptic_ulcer               8.399306
hla_match_a_low            8.298611
arrhythmia                 7.645833
rheum_issue                7

In [14]:
df.duplicated().sum()


0

In [16]:
# Drop columns with more than 35% missing values
columns_to_drop = ["tce_match", "mrd_hct", "cyto_score_detail", "tce_div_match", "tce_imm_match"]
df = df.drop(columns=columns_to_drop)
df.shape

(28800, 55)

In [18]:
# Fill categorical missing values with mode 

categorical_columns = df.select_dtypes(include = ["object"]).columns
categorical_columns

Index(['dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'tbi_status',
       'arrhythmia', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe',
       'prim_disease_hct', 'cmv_status', 'rituximab', 'prod_type',
       'conditioning_intensity', 'ethnicity', 'obesity', 'in_vivo_tcd',
       'hepatic_severe', 'prior_tumor', 'peptic_ulcer', 'gvhd_proph',
       'rheum_issue', 'sex_match', 'race_group', 'hepatic_mild',
       'donor_related', 'melphalan_dose', 'cardiac', 'pulm_moderate'],
      dtype='object')

In [20]:
for i in categorical_columns:
    df[i].fillna(df[i].mode()[0], inplace = True)

/var/folders/f1/f5y19fcx7070w2xg9472pbrm0000gn/T/ipykernel_11670/1420029020.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0], inplace = True)


In [22]:
# Fill numerical missing values with median

numerical_columns = df.select_dtypes(include = ["number"]).columns
numerical_columns

Index(['ID', 'hla_match_c_high', 'hla_high_res_8', 'hla_low_res_6',
       'hla_high_res_6', 'hla_high_res_10', 'hla_match_dqb1_high',
       'hla_nmdp_6', 'hla_match_c_low', 'hla_match_drb1_low',
       'hla_match_dqb1_low', 'year_hct', 'hla_match_a_high', 'donor_age',
       'hla_match_b_low', 'age_at_hct', 'hla_match_a_low', 'hla_match_b_high',
       'comorbidity_score', 'karnofsky_score', 'hla_low_res_8',
       'hla_match_drb1_high', 'hla_low_res_10', 'efs', 'efs_time'],
      dtype='object')

In [24]:
df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].median())

In [26]:
df.isnull().sum()

ID                        0
dri_score                 0
psych_disturb             0
cyto_score                0
diabetes                  0
hla_match_c_high          0
hla_high_res_8            0
tbi_status                0
arrhythmia                0
hla_low_res_6             0
graft_type                0
vent_hist                 0
renal_issue               0
pulm_severe               0
prim_disease_hct          0
hla_high_res_6            0
cmv_status                0
hla_high_res_10           0
hla_match_dqb1_high       0
hla_nmdp_6                0
hla_match_c_low           0
rituximab                 0
hla_match_drb1_low        0
hla_match_dqb1_low        0
prod_type                 0
conditioning_intensity    0
ethnicity                 0
year_hct                  0
obesity                   0
in_vivo_tcd               0
hla_match_a_high          0
hepatic_severe            0
donor_age                 0
prior_tumor               0
hla_match_b_low           0
peptic_ulcer        

In [30]:
cat = []
num = []

for i in df.columns:
    if df[i].nunique() < 10:
        print(i,df[i].nunique(), df[i].unique())
        cat.append(i)
    else:
        num.append(i)

psych_disturb 3 ['No' 'Not done' 'Yes']
cyto_score 7 ['Poor' 'Intermediate' 'Other' 'Favorable' 'TBD' 'Normal' 'Not tested']
diabetes 3 ['No' 'Yes' 'Not done']
hla_match_c_high 3 [2. 1. 0.]
hla_high_res_8 7 [8. 7. 5. 6. 4. 3. 2.]
tbi_status 8 ['No TBI' 'TBI +- Other, >cGy' 'TBI + Cy +- Other' 'TBI +- Other, <=cGy'
 'TBI +- Other, unknown dose' 'TBI +- Other, -cGy, fractionated'
 'TBI +- Other, -cGy, single' 'TBI +- Other, -cGy, unknown dose']
arrhythmia 3 ['No' 'Yes' 'Not done']
hla_low_res_6 5 [6. 4. 3. 5. 2.]
graft_type 2 ['Bone marrow' 'Peripheral blood']
vent_hist 2 ['No' 'Yes']
renal_issue 3 ['No' 'Yes' 'Not done']
pulm_severe 3 ['No' 'Yes' 'Not done']
hla_high_res_6 6 [6. 5. 3. 4. 2. 0.]
cmv_status 4 ['+/+' '-/+' '-/-' '+/-']
hla_high_res_10 8 [10.  8.  6.  9.  5.  7.  4.  3.]
hla_match_dqb1_high 3 [2. 1. 0.]
hla_nmdp_6 5 [6. 5. 3. 4. 2.]
hla_match_c_low 3 [2. 1. 0.]
rituximab 2 ['No' 'Yes']
hla_match_drb1_low 2 [2. 1.]
hla_match_dqb1_low 3 [2. 1. 0.]
prod_type 2 ['BM' 'PB']
cond

In [32]:
cat

['psych_disturb',
 'cyto_score',
 'diabetes',
 'hla_match_c_high',
 'hla_high_res_8',
 'tbi_status',
 'arrhythmia',
 'hla_low_res_6',
 'graft_type',
 'vent_hist',
 'renal_issue',
 'pulm_severe',
 'hla_high_res_6',
 'cmv_status',
 'hla_high_res_10',
 'hla_match_dqb1_high',
 'hla_nmdp_6',
 'hla_match_c_low',
 'rituximab',
 'hla_match_drb1_low',
 'hla_match_dqb1_low',
 'prod_type',
 'conditioning_intensity',
 'ethnicity',
 'obesity',
 'in_vivo_tcd',
 'hla_match_a_high',
 'hepatic_severe',
 'prior_tumor',
 'hla_match_b_low',
 'peptic_ulcer',
 'hla_match_a_low',
 'rheum_issue',
 'sex_match',
 'hla_match_b_high',
 'race_group',
 'karnofsky_score',
 'hepatic_mild',
 'donor_related',
 'melphalan_dose',
 'hla_low_res_8',
 'cardiac',
 'hla_match_drb1_high',
 'pulm_moderate',
 'hla_low_res_10',
 'efs']

In [34]:
num

['ID',
 'dri_score',
 'prim_disease_hct',
 'year_hct',
 'donor_age',
 'age_at_hct',
 'gvhd_proph',
 'comorbidity_score',
 'efs_time']

In [40]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Identify categorical and numerical columns
categorical_cols = df.select_dtypes(include=["object"]).columns
numerical_cols = df.select_dtypes(include=["number"]).columns

# One-Hot Encode categorical columns
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded_categorical = encoder.fit_transform(df[categorical_cols])
encoded_categorical_df = pd.DataFrame(encoded_categorical, columns=encoder.get_feature_names_out(categorical_cols))


# Combine encoded categorical and scaled numerical data
df_preprocessed = pd.concat([df, encoded_categorical_df], axis=1)



In [42]:
columns_to_drop = df_preprocessed.select_dtypes(include=["object"]).columns

In [154]:
columns_to_drop

Index(['dri_score', 'psych_disturb', 'cyto_score', 'diabetes', 'tbi_status',
       'arrhythmia', 'graft_type', 'vent_hist', 'renal_issue', 'pulm_severe',
       'prim_disease_hct', 'cmv_status', 'rituximab', 'prod_type',
       'conditioning_intensity', 'ethnicity', 'obesity', 'in_vivo_tcd',
       'hepatic_severe', 'prior_tumor', 'peptic_ulcer', 'gvhd_proph',
       'rheum_issue', 'sex_match', 'race_group', 'hepatic_mild',
       'donor_related', 'melphalan_dose', 'cardiac', 'pulm_moderate'],
      dtype='object')

In [46]:
df_preprocessed = df_preprocessed.drop(columns=columns_to_drop)

In [151]:
df_preprocessed.columns

Index(['ID', 'hla_match_c_high', 'hla_high_res_8', 'hla_low_res_6',
       'hla_high_res_6', 'hla_high_res_10', 'hla_match_dqb1_high',
       'hla_nmdp_6', 'hla_match_c_low', 'hla_match_drb1_low',
       ...
       'donor_related_Related', 'donor_related_Unrelated',
       'melphalan_dose_MEL', 'melphalan_dose_N/A, Mel not given', 'cardiac_No',
       'cardiac_Not done', 'cardiac_Yes', 'pulm_moderate_No',
       'pulm_moderate_Not done', 'pulm_moderate_Yes'],
      dtype='object', length=163)

In [51]:
x = df_preprocessed.drop(columns=["efs", "efs_time"])  # Features
y = df_preprocessed[["efs"]]  # Target

In [144]:
x

ID  hla_match_c_high  hla_high_res_8  hla_low_res_6  hla_high_res_6  \
0          0               2.0             8.0            6.0             6.0   
1          1               2.0             8.0            6.0             6.0   
2          2               2.0             8.0            6.0             6.0   
3          3               2.0             8.0            6.0             6.0   
4          4               2.0             8.0            6.0             6.0   
...      ...               ...             ...            ...             ...   
28795  28795               2.0             8.0            6.0             6.0   
28796  28796               1.0             4.0            5.0             3.0   
28797  28797               2.0             8.0            6.0             6.0   
28798  28798               1.0             4.0            3.0             3.0   
28799  28799               2.0             8.0            6.0             6.0   

       hla_high_res_10  hla_match_dqb1_high  hla_nmdp_6  hla_match_c_low  \
0                 10.0                  2.0         6.0              2.0   
1                 10.0                  2.0         6.0              2.0   
2                 10.0                  2.0         6.0              2.0   
3                 10.0                  2.0         6.0              2.0   
4                 10.0                  2.0         5.0              2.0   
...                ...                  ...         ...              ...   
28795             10.0                  2.0         6.0              2.0   
28796              6.0                  2.0         4.0              1.0   
28797             10.0                  2.0         6.0              2.0   
28798              5.0                  1.0         3.0              1.0   
28799             10.0                  2.0         6.0              2.0   

       hla_match_drb1_low  ...  donor_related_Related  \
0                     2.0  ...                    0.0   
1                     2.0  ...                    1.0   
2                     2.0  ...                    1.0   
3                     2.0  ...                    0.0   
4                     2.0  ...                    1.0   
...                   ...  ...                    ...   
28795                 2.0  ...                    1.0   
28796                 2.0  ...                    1.0   
28797                 2.0  ...                    0.0   
28798                 1.0  ...                    1.0   
28799                 2.0  ...                    1.0   

       donor_related_Unrelated  melphalan_dose_MEL  \
0                          1.0                 0.0   
1                          0.0                 0.0   
2                          0.0                 0.0   
3                          1.0                 0.0   
4                          0.0                 1.0   
...                        ...                 ...   
28795                      0.0                 0.0   
28796                      0.0                 0.0   
28797                      1.0                 0.0   
28798                      0.0                 1.0   
28799                      0.0                 1.0   

       melphalan_dose_N/A, Mel not given  cardiac_No  cardiac_Not done  \
0                                    1.0         1.0               0.0   
1                                    1.0         1.0               0.0   
2                                    1.0         1.0               0.0   
3                                    1.0         1.0               0.0   
4                                    0.0         1.0               0.0   
...                                  ...         ...               ...   
28795                                1.0         1.0               0.0   
28796                                1.0         0.0               0.0   
28797                                1.0         1.0               0.0   
28798                                0.0         1

In [55]:
X = x.values
Y = y.values

In [57]:
Y

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [59]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X,Y, test_size = 0.3, random_state = 0)

In [61]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(20160, 161)
(8640, 161)
(20160, 1)
(8640, 1)


# Logistic Regression

In [64]:
from sklearn.linear_model import LogisticRegression

In [66]:
model = LogisticRegression()
model.fit(x_train,y_train)
y_train_predicted = model.predict(x_train)
y_test_predicted = model.predict(x_test)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [68]:
from sklearn.metrics import classification_report ,accuracy_score,precision_score,recall_score,confusion_matrix

In [70]:
print("Model Performance: ")
print("Training accuracy: ",accuracy_score(y_train,y_train_predicted))
print("Training precision: ", precision_score(y_train, y_train_predicted))
print("Training recall: ", recall_score(y_train, y_train_predicted))
print(confusion_matrix(y_train, y_train_predicted))
print("Training classification report: ",classification_report(y_train, y_train_predicted))

Model Performance: 
Training accuracy:  0.6242063492063492
Training precision:  0.6298061894341982
Training recall:  0.7394934850431272
[[4525 4737]
 [2839 8059]]
Training classification report:                precision    recall  f1-score   support

         0.0       0.61      0.49      0.54      9262
         1.0       0.63      0.74      0.68     10898

    accuracy                           0.62     20160
   macro avg       0.62      0.61      0.61     20160
weighted avg       0.62      0.62      0.62     20160



In [72]:
# Test 

#  Accuracy > 80% 

print("Model Performance: ")
print("Testing accuracy: ",accuracy_score(y_test,y_test_predicted))
print("Testing precision: ", precision_score(y_test,y_test_predicted))
print("Testing recall: ", recall_score(y_test,y_test_predicted))
print(confusion_matrix(y_test,y_test_predicted))
print("Testing classification report: ",classification_report(y_test,y_test_predicted))



Model Performance: 
Testing accuracy:  0.6212962962962963
Testing precision:  0.6235038084874864
Testing recall:  0.7419076391886059
[[1930 2076]
 [1196 3438]]
Testing classification report:                precision    recall  f1-score   support

         0.0       0.62      0.48      0.54      4006
         1.0       0.62      0.74      0.68      4634

    accuracy                           0.62      8640
   macro avg       0.62      0.61      0.61      8640
weighted avg       0.62      0.62      0.61      8640



# KNN Classifier

In [75]:
from sklearn.neighbors import KNeighborsClassifier

In [77]:
knn_model = KNeighborsClassifier(9)
knn_model.fit(x_train, y_train)
ytrain_knn_predicted = knn_model.predict(x_train)
ytrain_knn_predicted

/opt/anaconda3/lib/python3.12/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([1., 0., 0., ..., 1., 1., 0.])

In [78]:
y_train

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [79]:
print("Model Performance: ")
print("Training accuracy: ",accuracy_score(y_train,ytrain_knn_predicted))
print("Training precision: ", precision_score(y_train, ytrain_knn_predicted))
print("Training recall: ", recall_score(y_train, ytrain_knn_predicted))
print(confusion_matrix(y_train, ytrain_knn_predicted))
print("Training classification report: ",classification_report(y_train,ytrain_knn_predicted))

Model Performance: 
Training accuracy:  0.6717261904761904
Training precision:  0.6796206144032231
Training recall:  0.7429803633694256
[[5445 3817]
 [2801 8097]]
Training classification report:                precision    recall  f1-score   support

         0.0       0.66      0.59      0.62      9262
         1.0       0.68      0.74      0.71     10898

    accuracy                           0.67     20160
   macro avg       0.67      0.67      0.67     20160
weighted avg       0.67      0.67      0.67     20160



In [80]:
y_test_knn_predicted = knn_model.predict(x_test)
y_test_knn_predicted

array([0., 1., 0., ..., 1., 1., 1.])

In [81]:
# Test 

#  Accuracy > 80% 

print("Model Performance: ")
print("Testing accuracy: ",accuracy_score(y_test,y_test_knn_predicted))
print("Testing precision: ", precision_score(y_test,y_test_knn_predicted))
print("Testing recall: ", recall_score(y_test,y_test_knn_predicted))
print(confusion_matrix(y_test,y_test_knn_predicted))
print("Testing classification report: ",classification_report(y_test,y_test_knn_predicted))


Model Performance: 
Testing accuracy:  0.5545138888888889
Testing precision:  0.5777381659734601
Testing recall:  0.6294777729823047
[[1874 2132]
 [1717 2917]]
Testing classification report:                precision    recall  f1-score   support

         0.0       0.52      0.47      0.49      4006
         1.0       0.58      0.63      0.60      4634

    accuracy                           0.55      8640
   macro avg       0.55      0.55      0.55      8640
weighted avg       0.55      0.55      0.55      8640



# Random Forest Classifier

In [86]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth = 10)

In [89]:
rf.fit(x_train, y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(max_depth=10)

In [91]:
y_train_rf_predicted = rf.predict(x_train)

In [92]:
y_test_rf_predicted = rf.predict(x_test)

In [93]:
from sklearn.metrics import accuracy_score, precision_score , recall_score ,confusion_matrix

In [98]:
print('Model Performance')
print('Training Accuracy:', accuracy_score(y_train,y_train_rf_predicted))
#print('Training Precision:', precision_score(y_train,y_train_predicted))
#print('Training Recall:',recall_score(y_train,y_train_predicted))
print('Training Confusion Matrix: ', confusion_matrix(y_train,y_train_rf_predicted))
print('Training classifiation_report:',classification_report(y_train,y_train_rf_predicted))

Model Performance
Training Accuracy: 0.719047619047619
Training Confusion Matrix:  [[5040 4222]
 [1442 9456]]
Training classifiation_report:               precision    recall  f1-score   support

         0.0       0.78      0.54      0.64      9262
         1.0       0.69      0.87      0.77     10898

    accuracy                           0.72     20160
   macro avg       0.73      0.71      0.70     20160
weighted avg       0.73      0.72      0.71     20160



In [100]:
print('Model Performance')
print('Testing Accuracy:', accuracy_score(y_test,y_test_rf_predicted))
#print('Testing Precision:', precision_score(y_test,y_test_predicted))
#print('Testing Recall:',recall_score(y_test,y_test_predicted))
print('Testing Confusion Matrix: ', confusion_matrix(y_test,y_test_rf_predicted))
print('Testing classifiation_report:',classification_report(y_test,y_test_rf_predicted))

Model Performance
Testing Accuracy: 0.6657407407407407
Testing Confusion Matrix:  [[1942 2064]
 [ 824 3810]]
Testing classifiation_report:               precision    recall  f1-score   support

         0.0       0.70      0.48      0.57      4006
         1.0       0.65      0.82      0.73      4634

    accuracy                           0.67      8640
   macro avg       0.68      0.65      0.65      8640
weighted avg       0.67      0.67      0.65      8640



# Decision tree classifier

In [103]:
from sklearn.tree import DecisionTreeClassifier

In [105]:
dtree= DecisionTreeClassifier(max_depth= 5)
dtree.fit(x_train,y_train)
y_train_predicted= dtree.predict(x_train)
y_test_predicted= dtree.predict(x_test)

In [107]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report

In [109]:
print('Model Performance')
print('Training Accuracy: ',accuracy_score(y_train,y_train_predicted))
print(confusion_matrix(y_train,y_train_predicted))
print(classification_report(y_train,y_train_predicted))

Model Performance
Training Accuracy:  0.6476190476190476
[[4772 4490]
 [2614 8284]]
              precision    recall  f1-score   support

         0.0       0.65      0.52      0.57      9262
         1.0       0.65      0.76      0.70     10898

    accuracy                           0.65     20160
   macro avg       0.65      0.64      0.64     20160
weighted avg       0.65      0.65      0.64     20160



In [111]:
print('Model Performance')
print('Testing Accuracy: ',accuracy_score(y_test,y_test_predicted))
print(confusion_matrix(y_test,y_test_predicted))
print(classification_report(y_test,y_test_predicted))

Model Performance
Testing Accuracy:  0.6417824074074074
[[2044 1962]
 [1133 3501]]
              precision    recall  f1-score   support

         0.0       0.64      0.51      0.57      4006
         1.0       0.64      0.76      0.69      4634

    accuracy                           0.64      8640
   macro avg       0.64      0.63      0.63      8640
weighted avg       0.64      0.64      0.64      8640



In [114]:
from sklearn.model_selection import GridSearchCV
clf = DecisionTreeClassifier()


In [116]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
}

In [118]:
grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)

In [120]:
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 10, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]},
             scoring='accuracy', verbose=1)

In [121]:
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

Best Parameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2}
Best Accuracy: 0.6350198412698412


In [124]:
best_model = grid_search.best_estimator_
test_score = best_model.score(x_test, y_test)
print("Test Accuracy:", test_score)

Test Accuracy: 0.6417824074074074


# Support Vector Machine

In [129]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train,y_train)
y_train_svm_predicted = svc.predict(x_train)
y_test_svm_predicted = svc.predict(x_test)


/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [130]:
from sklearn.metrics import accuracy_score, precision_score , recall_score ,confusion_matrix

print('Model Performance')
print('Training Accuracy:', accuracy_score(y_train,y_train_svm_predicted))
#print('Training Precision:', precision_score(y_train,y_train_predicted))
#print('Training Recall:',recall_score(y_train,y_train_predicted))
print('Training Confusion Matrix: ', confusion_matrix(y_train,y_train_svm_predicted))
print('Training classifiation_report:',classification_report(y_train,y_train_svm_predicted))

Model Performance
Training Accuracy: 0.5405753968253968
Training Confusion Matrix:  [[    0  9262]
 [    0 10898]]
Training classifiation_report:               precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      9262
         1.0       0.54      1.00      0.70     10898

    accuracy                           0.54     20160
   macro avg       0.27      0.50      0.35     20160
weighted avg       0.29      0.54      0.38     20160



/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [131]:
print('Model Performance')
print('Testing Accuracy:', accuracy_score(y_test,y_test_svm_predicted))
#print('Testing Precision:', precision_score(y_test,y_test_predicted))
#print('Testing Recall:',recall_score(y_test,y_test_predicted))
print('Testing Confusion Matrix: ', confusion_matrix(y_test,y_test_svm_predicted))
print('Testing classifiation_report:',classification_report(y_test,y_test_svm_predicted))

Model Performance
Testing Accuracy: 0.5363425925925925
Testing Confusion Matrix:  [[   0 4006]
 [   0 4634]]
Testing classifiation_report:               precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      4006
         1.0       0.54      1.00      0.70      4634

    accuracy                           0.54      8640
   macro avg       0.27      0.50      0.35      8640
weighted avg       0.29      0.54      0.37      8640



/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
